### ISSUE TITLE
This isn't going to be used as a library by everyone so LGPL isn't needed

### ISSUE THREAD

**Issue by obj-obj** [EnyCode/RoughlyEnoughSkyblock#2]
This isn't a library so LGPL isn't really valid, might be a good idea to switch to GPL or AGPL instead

**Comment by EnyCode** [comment]
Yeah, im thinking MIT or something, the status bars have definitely moved past skyblocker's code.

**Comment by obj-obj** [comment]
Dual MIT/APACHE might be a good idea

**Comment by EnyCode** [comment]
dual license? how does that work and what could the benefits be?

**Comment by obj-obj** [comment]
I don't know exactly, but Rust and other projects use it so there must be some benefits. Theres a page about that here from other project converting from MIT to dual license: https://github.com/bevyengine/bevy/issues/2373

**Comment by EnyCode** [comment]
interesting, i didnt know bevy was licensed under that. i'll switch over before i press pause on this. thanks for the suggestion!
